# Nifty 500 Strategy Scanner

Runs the 10-step trend-breakout-retest pipeline across the Nifty 500 universe using free Yahoo Finance data (via `yfinance`).

**Before running:** make sure the following files are in the SAME FOLDER as this notebook:
`pipeline.py`, `indicators.py`, `trend_filter.py`, `consolidation.py`, `breakout.py`, `momentum.py`, `volume_confirm.py`, `entry_retest.py`, `risk_management.py`

Run the cells in order, top to bottom.

## Step 0 — Point Python to your "Market Data" folder

This makes sure Python can find `pipeline.py` and the other strategy files, regardless of where this notebook itself is saved. Run this FIRST, before anything else.

In [ ]:
import os
import sys
import glob

# --- Robust auto-locate: finds pipeline.py even if Desktop is redirected
# (common on Windows with OneDrive) or the folder name differs slightly ---

home = os.path.expanduser("~")

candidate_paths = [
    os.path.join(home, "Desktop", "Market Data"),
    os.path.join(home, "OneDrive", "Desktop", "Market Data"),
]
# Also catch OneDrive folders named like "OneDrive - CompanyName"
candidate_paths += glob.glob(os.path.join(home, "OneDrive*", "Desktop", "Market Data"))

found_folder = None
for path in candidate_paths:
    if os.path.isfile(os.path.join(path, "pipeline.py")):
        found_folder = path
        break

# If none of the obvious guesses worked, search the whole home folder
# (this can take a few seconds but is thorough)
if not found_folder:
    print("Not found in common locations - searching your whole user folder for pipeline.py...")
    for root, dirs, files in os.walk(home):
        # skip huge/irrelevant system folders to keep this fast
        dirs[:] = [d for d in dirs if d not in (
            "Library", "AppData", "node_modules", ".git", "anaconda3", "miniconda3"
        )]
        if "pipeline.py" in files:
            found_folder = root
            break

if found_folder:
    os.chdir(found_folder)
    sys.path.insert(0, found_folder)
    print(f"FOUND pipeline.py in: {found_folder}")
    print(f"Working directory set to: {os.getcwd()}")
    print("\nFiles in this folder:")
    for f in sorted(os.listdir(found_folder)):
        print(f"  - {f}")
else:
    print("COULD NOT FIND pipeline.py anywhere in your user folder.")
    print("This means the file may not have actually been saved/downloaded yet,")
    print("or it's in a location this search didn't cover (e.g. an external drive).")
    print("\nRun this in a new cell to search manually:")
    print('  for root, dirs, files in os.walk("/"):')
    print('      if "pipeline.py" in files: print(root)')
    print("\n(Note: searching from '/' can be slow - Ctrl+C / Interrupt Kernel to stop it.)")

FOUND pipeline.py in: /Users/sairitdey/Desktop/Market Data
Working directory set to: /Users/sairitdey/Desktop/Market data

Files in this folder:
  - .DS_Store
  - .ipynb_checkpoints
  - Data colllection
  - __pycache__
  - breakout.py
  - consolidation.py
  - entry_retest.py
  - files.zip
  - indicators.py
  - momentum.py
  - mtf_swing_strategy_v2.ipynb
  - mtf_swing_strategy_v2.py
  - nifty500_scan_results.csv
  - nifty500_scanner.ipynb
  - pipeline.py
  - risk_management.py
  - scan_nifty500.py
  - trading_screener.py
  - trend_filter.py
  - universe_cache
  - volume_confirm.py

## Step 1 — Install required packages
Run this once. If already installed, it's safe to skip or re-run.

In [ ]:
!pip install yfinance pandas requests --quiet

## Step 2 — Check that the strategy modules are found
This confirms `pipeline.py` and its dependencies are in the same folder as this notebook.

In [ ]:
import os

required_files = [
    "pipeline.py", "indicators.py", "trend_filter.py", "consolidation.py",
    "breakout.py", "momentum.py", "volume_confirm.py", "entry_retest.py",
    "risk_management.py",
]

missing = [f for f in required_files if not os.path.exists(f)]

if missing:
    print("MISSING FILES - copy these into this notebook's folder before continuing:")
    for f in missing:
        print(f"  - {f}")
else:
    print("All strategy modules found. You're good to continue.")

All strategy modules found. You're good to continue.

## Step 3 — Imports

In [ ]:
import time
import io
import requests
import pandas as pd
import yfinance as yf

from pipeline import run_pipeline

pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 150)

## Step 4 — Get the Nifty 500 symbol list
Tries to fetch the live list from NSE. NSE often blocks non-browser requests, so a fallback list is used if that fails - edit `FALLBACK_SYMBOLS` below with the full list (downloaded manually from NSE) for a complete scan.

In [ ]:
NIFTY500_LIST_URL = "https://archives.nseindia.com/content/indices/ind_nifty500list.csv"

FALLBACK_SYMBOLS = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR",
    "ITC", "SBIN", "BHARTIARTL", "BAJFINANCE", "HINDZINC", "TATASTEEL",
    # Extend this list with more Nifty 500 symbols as needed
]

def get_nifty500_symbols():
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        resp = requests.get(NIFTY500_LIST_URL, headers=headers, timeout=10)
        resp.raise_for_status()
        df = pd.read_csv(io.StringIO(resp.text))
        symbols = df["Symbol"].tolist()
        print(f"Fetched {len(symbols)} symbols from NSE.")
        return symbols
    except Exception as e:
        print(f"Could not fetch NSE list automatically ({e}).")
        print(f"Using fallback list of {len(FALLBACK_SYMBOLS)} symbols instead.")
        return FALLBACK_SYMBOLS

symbols = get_nifty500_symbols()
print(f"\nTotal symbols to scan: {len(symbols)}")

Fetched 500 symbols from NSE.

Total symbols to scan: 500

## Step 5 — OHLCV fetch function (Yahoo Finance)

In [ ]:
def fetch_ohlcv_yfinance(symbol, period="90d", interval="60m"):
    ticker = f"{symbol}.NS"
    data = yf.download(ticker, period=period, interval=interval, progress=False)

    if data.empty:
        raise ValueError(f"No data returned for {ticker}")

    # yfinance returns MultiIndex columns like ('Close', 'RELIANCE.NS') -
    # flatten to just the field name before lowercasing.
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.get_level_values(0)

    data = data.rename(columns=str.lower)
    data = data[["open", "high", "low", "close", "volume"]]
    return data

## Step 6 — Quick test on a single stock
Run this first to sanity-check everything works before scanning all 500.

In [ ]:
test_df = fetch_ohlcv_yfinance("RELIANCE")
print(test_df.shape)
test_df.tail()

(610, 5)

Price                             open         high          low        close   volume
Datetime
2026-09-03 15:15:00+05:30  1309.099976  1309.099976  1302.500000  1302.500000   690251
2026-09-04 09:15:00+05:30  1304.099976  1332.199951  1304.099976  1327.000000  3550780
2026-09-04 10:15:00+05:30  1326.800049  1328.900024  1325.099976  1325.500000  1233518
2026-09-04 11:15:00+05:30  1325.500000  1333.000000  1325.000000  1330.099976  2137828
2026-09-04 12:15:00+05:30  1330.199951  1332.400024  1329.099976  1329.099976   831414

In [ ]:
test_signals = run_pipeline(test_df, symbol="RELIANCE")
print(f"Signals found: {len(test_signals)}")
test_signals

Signals found: 0

[]

## Step 7 — Full scan function

In [ ]:
def scan(symbols, cutoff_date=None, freshness_days=3, drop_incomplete_candle=True):
    """
    cutoff_date=None -> automatically uses TODAY'S date (IST), every run.
    Pass an explicit "YYYY-MM-DD" string to check a specific past date instead.
    drop_incomplete_candle=True -> removes the most recent candle if it's
    still forming (hasn't hit the full hour yet), so you don't act on a
    signal that could still change shape before the candle closes.
    """
    if cutoff_date is None:
        cutoff = pd.Timestamp.now(tz="Asia/Kolkata").normalize()
    else:
        cutoff = pd.Timestamp(cutoff_date)

    fresh_cutoff = cutoff - pd.Timedelta(days=freshness_days)

    all_signals = []

    for i, symbol in enumerate(symbols):
        try:
            df = fetch_ohlcv_yfinance(symbol)

            # Yahoo returns timezone-aware timestamps (Asia/Kolkata).
            if df.index.tz is not None:
                cutoff_tz = cutoff.tz_localize(df.index.tz) if cutoff.tz is None else cutoff.tz_convert(df.index.tz)
                fresh_cutoff_tz = fresh_cutoff.tz_localize(df.index.tz) if fresh_cutoff.tz is None else fresh_cutoff.tz_convert(df.index.tz)
            else:
                cutoff_tz = cutoff
                fresh_cutoff_tz = fresh_cutoff

            # Drop the current in-progress hourly candle if it hasn't closed yet.
            if drop_incomplete_candle and len(df) > 0:
                now_tz = pd.Timestamp.now(tz="Asia/Kolkata")
                now_compare = now_tz.tz_convert(df.index.tz) if df.index.tz is not None else now_tz.tz_localize(None)
                last_candle_start = df.index[-1]
                candle_end = last_candle_start + pd.Timedelta(hours=1)
                if candle_end > now_compare:
                    df = df.iloc[:-1]

            df = df[df.index <= cutoff_tz]  # avoid look-ahead past cutoff

            signals = run_pipeline(df, symbol=symbol)
            fresh = [s for s in signals if fresh_cutoff_tz <= s["date"] <= cutoff_tz]
            all_signals.extend(fresh)

            status = f"{len(fresh)} fresh signal(s)" if fresh else "no signal"
            print(f"[{i+1}/{len(symbols)}] {symbol}: {status}")

        except Exception as e:
            print(f"[{i+1}/{len(symbols)}] {symbol}: ERROR - {e}")

        time.sleep(0.5)  # avoid Yahoo rate limiting

    if not all_signals:
        print("\nNo stocks currently pass the full 10-step criteria.")
        return pd.DataFrame()

    result_df = pd.DataFrame(all_signals)
    result_df.sort_values("date", ascending=False, inplace=True)
    return result_df.reset_index(drop=True)

## Step 8 — Run the full scan
This will take a few minutes depending on how many symbols are in your list (rate-limited to be polite to Yahoo's servers).

In [ ]:
# cutoff_date=None -> uses today's date automatically, every run.
# Pass cutoff_date="2026-08-28" (or any date) to check a specific past day instead.
results = scan(symbols, cutoff_date=None, freshness_days=3)

[1/500] 360ONE: no signal
[2/500] 3MINDIA: no signal
[3/500] ABB: no signal
[4/500] ACC: no signal
[5/500] ACMESOLAR: no signal
[6/500] AIAENG: no signal
[7/500] APLAPOLLO: no signal
[8/500] AUBANK: no signal
[9/500] AWL: no signal
[10/500] AADHARHFC: no signal
[11/500] AARTIIND: no signal
[12/500] AAVAS: no signal
[13/500] ABBOTINDIA: no signal
[14/500] ACE: no signal
[15/500] ACUTAAS: no signal
[16/500] ADANIENSOL: no signal
[17/500] ADANIENT: no signal
[18/500] ADANIGREEN: no signal
[19/500] ADANIPORTS: no signal
[20/500] ADANIPOWER: no signal
[21/500] ATGL: no signal
[22/500] ABCAPITAL: no signal
[23/500] ABFRL: no signal
[24/500] ABLBL: no signal
[25/500] ABREL: no signal
[26/500] ABSLAMC: no signal
[27/500] CPPLUS: no signal
[28/500] AEGISLOG: no signal
[29/500] AEGISVOPAK: no signal
[30/500] AFCONS: 1 fresh signal(s)
[31/500] AFFLE: no signal
[32/500] AJANTPHARM: no signal
[33/500] ALKEM: no signal
[34/500] ABDL: no signal
[35/500] ARE&M: no signal
[36/500] AMBER: no signal
[37/500] AMBUJACEM: no signal
[38/500] ANANDRATHI: no signal
[39/500] ANANTRAJ: no signal
[40/500] ANGELONE: no signal
[41/500] ANTHEM: no signal
[42/500] ANURAS: no signal
[43/500] APARINDS: no signal
[44/500] APOLLOHOSP: no signal
[45/500] APOLLOTYRE: no signal
[46/500] APTUS: no signal
[47/500] ASAHIINDIA: no signal
[48/500] ASHOKLEY: no signal
[49/500] ASIANPAINT: no signal
[50/500] ASTERDM: no signal
[51/500] ASTRAL: no signal
[52/500] ATHERENERG: no signal
[53/500] ATUL: no signal
[54/500] AUROPHARMA: no signal
[55/500] AIIL: no signal
[56/500] DMART: no signal
[57/500] AXISBANK: no signal
[58/500] BEML: no signal
[59/500] BLS: no signal
[60/500] BSE: no signal
[61/500] BAJAJ-AUTO: no signal
[62/500] BAJFINANCE: no signal
[63/500] BAJAJFINSV: no signal
[64/500] BAJAJHLDNG: no signal
[65/500] BAJAJHFL: no signal
[66/500] BALKRISIND: no signal
[67/500] BALRAMCHIN: no signal
[68/500] BANDHANBNK: no signal
[69/500] BANKBARODA: no signal
[70/500] BANKINDIA: no signal
[71/500] MAHABANK: no signal
[72/500] BATAINDIA: no signal
[73/500] BAYERCROP: no signal
[74/500] BELRISE: no signal
[75/500] BERGEPAINT: no signal
[76/500] BDL: no signal
[77/500] BEL: no signal
[78/500] BHARATFORG: no signal
[79/500] BHEL: no signal
[80/500] BPCL: no signal
[81/500] BHARTIARTL: no signal
[82/500] BHARTIHEXA: no signal
[83/500] BIKAJI: no signal
[84/500] GROWW: no signal
[85/500] BIOCON: no signal
[86/500] BSOFT: no signal
[87/500] BLUEDART: no signal
[88/500] BLUEJET: no signal
[89/500] BLUESTARCO: no signal
[90/500] BBTC: no signal
[91/500] BOSCHLTD: no signal
[92/500] FIRSTCRY: no signal
[93/500] BRIGADE: no signal
[94/500] BRITANNIA: no signal
[95/500] MAPMYINDIA: no signal
[96/500] CCL: no signal
[97/500] CESC: no signal
[98/500] CGPOWER: no signal
[99/500] CIEINDIA: no signal
[100/500] CRISIL: no signal
[101/500] CANFINHOME: no signal
[102/500] CANBK: no signal
[103/500] CANHLIFE: no signal
[104/500] CAPLIPOINT: no signal
[105/500] CGCL: no signal
[106/500] CARBORUNIV: no signal
[107/500] CARTRADE: no signal
[108/500] CASTROLIND: no signal
[109/500] CEATLTD: no signal
[110/500] CEMPRO: no signal
[111/500] CENTRALBK: no signal
[112/500] CDSL: no signal
[113/500] CHALET: no signal
[114/500] CHAMBLFERT: no signal
[115/500] CHENNPETRO: no signal
[116/500] CHOICEIN: no signal
[117/500] CHOLAHLDNG: no signal
[118/500] CHOLAFIN: no signal
[119/500] CIPLA: no signal
[120/500] CUB: no signal
[121/500] CLEAN: no signal
[122/500] COALINDIA: no signal
[123/500] COCHINSHIP: no signal
[124/500] COFORGE: no signal
[125/500] COHANCE: no signal
[126/500] COLPAL: no signal
[127/500] CAMS: no signal
[128/500] CONCORDBIO: no signal
[129/500] CONCOR: no signal
[130/500] COROMANDEL: no signal
[131/500] CRAFTSMAN: no signal
[132/500] CREDITACC: no signal
[133/500] CROMPTON: no signal
[134/500] CUMMINSIND: no signal
[135/500] CYIENT: no signal
[136/500] DCMSHRIRAM: no signal
[137/500] DLF: no signal
[138/500] DOMS: no signal
[139/500] DABUR: no signal
[140/500] DALBHARAT: no signal
[141/500] DATAPATTNS: no signal
[142/500] DEEPAKFERT: no signal
[143/500] DEEPAKNTR: no signal
[144/500] DELHIVERY: no signal
[145/500] DEVYANI: no signal
[146/500] DIVISLAB: no signal
[147/500] DIXON: no signal
[148/500] LALPATHLAB: no signal
[149/500] DRREDDY: no signal
[150/500] EIDPARRY: no signal
[151/500] EIHOTEL: no signal
[152/500] EICHERMOT: no signal
[153/500] ELECON: no signal
[154/500] ELGIEQUIP: no signal
[155/500] EMAMILTD: no signal
[156/500] EMCURE: no signal
[157/500] EMMVEE: no signal
[158/500] ENDURANCE: no signal
[159/500] ENGINERSIN: no signal
[160/500] ERIS: no signal
[161/500] ESCORTS: no signal
[162/500] ETERNAL: no signal
[163/500] EXIDEIND: no signal
[164/500] NYKAA: no signal
[165/500] FEDERALBNK: no signal
[166/500] FACT: no signal
[167/500] FINCABLES: no signal
[168/500] FSL: no signal
[169/500] FIVESTAR: no signal
[170/500] FORCEMOT: no signal
[171/500] FORTIS: no signal
[172/500] GAIL: no signal
[173/500] GVT&D: no signal
[174/500] GMRAIRPORT: no signal
[175/500] GABRIEL: no signal
[176/500] GALLANTT: no signal
[177/500] GRSE: no signal
[178/500] GICRE: no signal
[179/500] GILLETTE: no signal
[180/500] GLAND: no signal
[181/500] GLAXO: no signal
[182/500] GLENMARK: no signal
[183/500] MEDANTA: no signal
[184/500] GODIGIT: no signal
[185/500] GPIL: no signal
[186/500] GODFRYPHLP: no signal
[187/500] GODREJCP: no signal
[188/500] GODREJIND: no signal
[189/500] GODREJPROP: no signal
[190/500] GRANULES: no signal
[191/500] GRAPHITE: no signal
[192/500] GRASIM: no signal
[193/500] GRAVITA: no signal
[194/500] GESHIP: no signal
[195/500] FLUOROCHEM: no signal
[196/500] GMDCLTD: no signal
[197/500] HEG: no signal
[198/500] HBLENGINE: no signal
[199/500] HCLTECH: no signal
[200/500] HDBFS: no signal
[201/500] HDFCAMC: no signal
[202/500] HDFCBANK: no signal
[203/500] HDFCLIFE: no signal
[204/500] HFCL: no signal
[205/500] HAVELLS: no signal
[206/500] HEROMOTOCO: no signal
[207/500] HEXT: no signal
[208/500] HSCL: no signal
[209/500] HINDALCO: no signal
[210/500] HAL: no signal
[211/500] HINDCOPPER: no signal
[212/500] HINDPETRO: no signal
[213/500] HINDUNILVR: no signal
[214/500] HINDZINC: no signal
[215/500] POWERINDIA: no signal
[216/500] HOMEFIRST: no signal
[217/500] HONASA: no signal
[218/500] HONAUT: no signal
[219/500] HUDCO: no signal
[220/500] HYUNDAI: no signal
[221/500] ICICIBANK: no signal
[222/500] ICICIGI: no signal
[223/500] ICICIAMC: no signal
[224/500] ICICIPRULI: no signal
[225/500] IDBI: no signal
[226/500] IDFCFIRSTB: no signal
[227/500] IFCI: no signal
[228/500] IIFL: no signal
[229/500] IRB: no signal
[230/500] IRCON: no signal
[231/500] ITCHOTELS: no signal
[232/500] ITC: no signal
[233/500] ITI: no signal
[234/500] INDGN: no signal
[235/500] INDIACEM: no signal
[236/500] INDIAMART: no signal
[237/500] INDIANB: no signal
[238/500] IEX: no signal
[239/500] INDHOTEL: no signal
[240/500] IOC: no signal
[241/500] IOB: no signal
[242/500] IRCTC: no signal
[243/500] IRFC: no signal
[244/500] IREDA: no signal
[245/500] IGL: no signal
[246/500] INDUSTOWER: no signal
[247/500] INDUSINDBK: no signal
[248/500] NAUKRI: no signal
[249/500] INFY: no signal
[250/500] INOXWIND: no signal
[251/500] INTELLECT: no signal
[252/500] INDIGO: no signal
[253/500] IGIL: no signal
[254/500] IKS: no signal
[255/500] IPCALAB: no signal
[256/500] JKCEMENT: no signal
[257/500] JBMA: no signal
[258/500] JKTYRE: no signal
[259/500] JMFINANCIL: no signal
[260/500] JSWCEMENT: no signal
[261/500] JSWDULUX: no signal
[262/500] JSWENERGY: no signal
[263/500] JSWINFRA: no signal
[264/500] JSWSTEEL: no signal
[265/500] JAINREC: no signal
[266/500] JPPOWER: no signal
[267/500] J&KBANK: no signal
[268/500] JINDALSAW: no signal
[269/500] JSL: no signal
[270/500] JINDALSTEL: no signal
[271/500] JIOFIN: no signal
[272/500] JUBLFOOD: no signal
[273/500] JUBLINGREA: no signal
[274/500] JUBLPHARMA: no signal

$JWL.NS: possibly delisted; no price data found  (period=90d)

1 Failed download:
['JWL.NS']: possibly delisted; no price data found  (period=90d)

[275/500] JWL: ERROR - No data returned for JWL.NS
[276/500] JYOTICNC: no signal
[277/500] KPRMILL: no signal
[278/500] KEI: no signal
[279/500] KPITTECH: no signal
[280/500] KAJARIACER: no signal
[281/500] KPIL: no signal
[282/500] KALYANKJIL: no signal
[283/500] KARURVYSYA: no signal
[284/500] KAYNES: no signal
[285/500] KEC: no signal
[286/500] KFINTECH: no signal
[287/500] KIRLOSENG: no signal
[288/500] KOTAKBANK: no signal
[289/500] KIMS: no signal
[290/500] LTF: no signal
[291/500] LTTS: no signal
[292/500] LGEINDIA: no signal
[293/500] LICHSGFIN: no signal
[294/500] LTFOODS: no signal
[295/500] LTM: no signal
[296/500] LT: no signal
[297/500] LATENTVIEW: no signal
[298/500] LAURUSLABS: no signal
[299/500] THELEELA: no signal
[300/500] LEMONTREE: no signal
[301/500] LENSKART: no signal
[302/500] LICI: no signal
[303/500] LINDEINDIA: no signal
[304/500] LLOYDSME: no signal
[305/500] LODHA: no signal
[306/500] LUPIN: no signal
[307/500] MMTC: no signal
[308/500] MRF: no signal
[309/500] MGL: no signal
[310/500] M&MFIN: no signal
[311/500] M&M: no signal
[312/500] MANAPPURAM: no signal
[313/500] MRPL: no signal
[314/500] MANKIND: no signal
[315/500] MARICO: no signal
[316/500] MARUTI: no signal
[317/500] MFSL: no signal
[318/500] MAXHEALTH: no signal
[319/500] MAZDOCK: no signal
[320/500] MEESHO: no signal
[321/500] MINDACORP: no signal
[322/500] MSUMI: no signal
[323/500] MOTILALOFS: no signal
[324/500] MPHASIS: no signal
[325/500] MCX: no signal
[326/500] MUTHOOTFIN: no signal
[327/500] NATCOPHARM: no signal
[328/500] NBCC: no signal
[329/500] NCC: no signal
[330/500] NHPC: no signal
[331/500] NLCINDIA: no signal
[332/500] NMDC: no signal
[333/500] NSLNISP: no signal
[334/500] NTPCGREEN: no signal
[335/500] NTPC: no signal
[336/500] NH: no signal
[337/500] NATIONALUM: no signal
[338/500] NAVA: no signal
[339/500] NAVINFLUOR: no signal
[340/500] NESTLEIND: no signal
[341/500] NETWEB: no signal
[342/500] NEULANDLAB: no signal
[343/500] NEWGEN: no signal
[344/500] NAM-INDIA: no signal
[345/500] NIVABUPA: no signal
[346/500] NUVAMA: no signal
[347/500] NUVOCO: no signal
[348/500] OBEROIRLTY: no signal
[349/500] ONGC: no signal
[350/500] OIL: no signal
[351/500] OLAELEC: no signal
[352/500] OLECTRA: no signal
[353/500] PAYTM: no signal
[354/500] ONESOURCE: no signal
[355/500] OFSS: no signal
[356/500] POLICYBZR: no signal
[357/500] PCBL: no signal
[358/500] PGEL: no signal
[359/500] PIIND: no signal
[360/500] PNBHOUSING: no signal
[361/500] PTCIL: no signal
[362/500] PVRINOX: no signal
[363/500] PAGEIND: no signal
[364/500] PARADEEP: no signal
[365/500] PATANJALI: no signal
[366/500] PERSISTENT: no signal
[367/500] PETRONET: no signal
[368/500] PFIZER: no signal
[369/500] PHOENIXLTD: no signal
[370/500] PWL: no signal
[371/500] PIDILITIND: no signal
[372/500] PINELABS: no signal
[373/500] PIRAMALFIN: no signal
[374/500] PPLPHARMA: no signal
[375/500] POLYMED: no signal
[376/500] POLYCAB: no signal
[377/500] POONAWALLA: no signal
[378/500] PFC: no signal
[379/500] POWERGRID: no signal
[380/500] PREMIERENE: no signal
[381/500] PRESTIGE: no signal
[382/500] PFOCUS: no signal
[383/500] PNB: no signal
[384/500] RRKABEL: no signal
[385/500] RBLBANK: no signal
[386/500] RECLTD: no signal
[387/500] RHIM: no signal
[388/500] RITES: no signal
[389/500] RADICO: no signal
[390/500] RVNL: no signal
[391/500] RAILTEL: no signal
[392/500] RAINBOW: no signal
[393/500] RKFORGE: no signal
[394/500] REDINGTON: no signal
[395/500] RELIANCE: no signal
[396/500] RPOWER: no signal
[397/500] SBFC: no signal
[398/500] SBICARD: no signal
[399/500] SBILIFE: no signal
[400/500] SJVN: no signal
[401/500] SRF: no signal
[402/500] SAGILITY: no signal
[403/500] SAILIFE: no signal
[404/500] SAMMAANCAP: no signal
[405/500] MOTHERSON: no signal
[406/500] SAPPHIRE: no signal
[407/500] SARDAEN: no signal
[408/500] SAREGAMA: no signal
[409/500] SCHAEFFLER: no signal
[410/500] SCHNEIDER: no signal
[411/500] SCI: no signal
[412/500] SHREECEM: no signal
[413/500] SHRIRAMFIN: no signal
[414/500] SHYAMMETL: no signal
[415/500] ENRIN: no signal
[416/500] SIEMENS: no signal
[417/500] SIGNATURE: no signal
[418/500] SOBHA: no signal
[419/500] SOLARINDS: no signal
[420/500] SONACOMS: no signal
[421/500] SONATSOFTW: no signal
[422/500] STARHEALTH: no signal
[423/500] SBIN: no signal
[424/500] SAIL: no signal
[425/500] SUMICHEM: no signal
[426/500] SUNPHARMA: no signal
[427/500] SUNTV: no signal
[428/500] SUNDARMFIN: no signal
[429/500] SUPREMEIND: no signal
[430/500] SPLPETRO: no signal
[431/500] SUZLON: no signal
[432/500] SWANCORP: no signal
[433/500] SWIGGY: no signal
[434/500] SYNGENE: no signal
[435/500] SYRMA: no signal
[436/500] TBOTEK: no signal
[437/500] TVSMOTOR: no signal
[438/500] TATACAP: 1 fresh signal(s)
[439/500] TATACHEM: no signal
[440/500] TATACOMM: no signal
[441/500] TCS: no signal
[442/500] TATACONSUM: no signal
[443/500] TATAELXSI: no signal
[444/500] TATAINVEST: no signal
[445/500] TMCV: no signal
[446/500] TMPV: no signal
[447/500] TATAPOWER: no signal
[448/500] TATASTEEL: no signal
[449/500] TATATECH: no signal
[450/500] TTML: no signal
[451/500] TECHM: no signal
[452/500] TECHNOE: no signal
[453/500] TEGA: no signal
[454/500] TEJASNET: no signal
[455/500] TENNIND: no signal
[456/500] NIACL: no signal
[457/500] RAMCOCEM: no signal
[458/500] THERMAX: no signal
[459/500] TIMKEN: no signal
[460/500] TITAGARH: no signal
[461/500] TITAN: no signal
[462/500] TORNTPHARM: no signal
[463/500] TORNTPOWER: no signal
[464/500] TARIL: no signal
[465/500] TRAVELFOOD: no signal
[466/500] TRENT: no signal
[467/500] TRIDENT: no signal
[468/500] TRITURBINE: no signal
[469/500] TIINDIA: no signal
[470/500] UCOBANK: no signal
[471/500] UNOMINDA: no signal
[472/500] UPL: no signal
[473/500] UTIAMC: no signal
[474/500] ULTRACEMCO: no signal
[475/500] UNIONBANK: no signal
[476/500] UBL: no signal
[477/500] UNITDSPR: no signal
[478/500] URBANCO: no signal
[479/500] USHAMART: no signal
[480/500] VTL: no signal
[481/500] VBL: no signal
[482/500] VEDL: no signal
[483/500] VIJAYA: no signal
[484/500] VMM: no signal
[485/500] IDEA: no signal
[486/500] VOLTAS: no signal
[487/500] WAAREEENER: no signal
[488/500] WELCORP: no signal
[489/500] WELSPUNLIV: no signal
[490/500] WHIRLPOOL: no signal
[491/500] WIPRO: no signal
[492/500] WOCKPHARMA: no signal
[493/500] YESBANK: no signal
[494/500] ZFCVINDIA: no signal
[495/500] ZEEL: no signal
[496/500] ZENTEC: no signal
[497/500] ZENSARTECH: no signal
[498/500] ZYDUSLIFE: no signal
[499/500] ZYDUSWELL: no signal
[500/500] ECLERX: no signal

## Diagnostic — confirm what date this actually ran against
Run this right after Step 8 to see exactly what 'now' and 'cutoff' the scan used.

In [ ]:
import pandas as pd
print('Current real time (IST):', pd.Timestamp.now(tz="Asia/Kolkata"))
print('Most recent date in your results:', results['date'].max() if not results.empty else 'no results')
print('\nIf the current time above is TODAY but results only show old dates,')
print('it means Step 8 was run earlier and not re-executed since - re-run Step 8.')

Current real time (IST): 2026-09-04 13:07:26.137837+05:30
Most recent date in your results: 2026-09-03 14:15:00+05:30

If the current time above is TODAY but results only show old dates,
it means Step 8 was run earlier and not re-executed since - re-run Step 8.

## Step 9 — View results

In [ ]:
if not results.empty:
    display(results)
else:
    print("No signals to display.")

    symbol                      date entry_mode   entry  stop_loss  target_1  target_2  risk_pct   atr  rvol       volume_grade  breakout_atr
0  TATACAP 2026-09-03 14:15:00+05:30  IMMEDIATE  372.55     368.82    377.13    380.57       1.0  2.29  2.14  STRONG (>=2x avg)          0.70
1   AFCONS 2026-09-03 11:15:00+05:30  IMMEDIATE  295.25     292.30    300.53    304.49       1.0  2.64  6.19  STRONG (>=2x avg)          2.88

## Step 10 — Save results to CSV (optional)

In [ ]:
if not results.empty:
    results.to_csv("nifty500_scan_results.csv", index=False)
    print("Saved to nifty500_scan_results.csv")

Saved to nifty500_scan_results.csv